const _ = require('lodash');
const JsonRpc = require('node-jsonrpc-request');

class BitcoinRpc {
  constructor(url) {
    this.jsonrpc = new JsonRpc(url);
  }
  
  async call() {
    let method = arguments[0];
    let params = [...arguments].splice(1);
    return this.jsonrpc.call(method, params);
  }
}

// bitcoin core v0.16.2
const methods = [
  'abandonTransaction',
  'abortRescan',
  'addMultiSigAddress',
  'addNode',
  'addWitnessAddress',
  'backupWallet',
  'bumpFee',
  'clearBanned',
  'combineRawTransaction',
  'createMultiSig',
  'createRawTransaction',
  'createWitnessAddress',
  'decodeRawTransaction',
  'decodeScript',
  'disconnectNode',
  'dumpPrivKey',
  'dumpWallet',
  'encryptWallet',
  'estimateFee',
  'estimatePriority',
  'estimateSmartFee',
  'estimateSmartPriority',
  'fundRawTransaction',
  'generate',
  'generateToAddress',
  'getAccount',
  'getAccountAddress',
  'getAddedNodeInfo',
  'getAddressesByAccount',
  'getBalance',
  'getBestBlockHash',
  'getBlock',
  'getBlockCount',
  'getBlockHash',
  'getBlockHeader',
  'getBlockTemplate',
  'getBlockchainInfo',
  'getChainTips',
  'getChainTxStats',
  'getConnectionCount',
  'getDifficulty',
  'getGenerate',
  'getHashesPerSec',
  'getInfo',
  'getMemoryInfo',
  'getMempoolAncestors',
  'getMempoolDescendants',
  'getMempoolEntry',
  'getMempoolInfo',
  'getMiningInfo',
  'getNetTotals',
  'getNetworkHashPs',
  'getNetworkInfo',
  'getNewAddress',
  'getPeerInfo',
  'getRawChangeAddress',
  'getRawMempool',
  'getRawTransaction',
  'getReceivedByAccount',
  'getReceivedByAddress',
  'getTransaction',
  'getTxOut',
  'getTxOutProof',
  'getTxOutSetInfo',
  'getUnconfirmedBalance',
  'getWalletInfo',
  'getWork',
  'help',
  'importAddress',
  'importMulti',
  'importPrivKey',
  'importPrunedFunds',
  'importPubKey',
  'importWallet',
  'keypoolRefill',
  'listAccounts',
  'listAddressGroupings',
  'listBanned',
  'listLockUnspent',
  'listReceivedByAccount',
  'listReceivedByAddress',
  'listSinceBlock',
  'listTransactions',
  'listUnspent',
  'listWallets',
  'lockUnspent',
  'move',
  'ping',
  'preciousBlock',
  'prioritiseTransaction',
  'pruneBlockchain',
  'removePrunedFunds',
  'rescanBlockchain',
  'saveMempool',
  'sendFrom',
  'sendMany',
  'sendRawTransaction',
  'sendToAddress',
  'setAccount',
  'setBan',
  'setGenerate',
  'setNetworkActive',
  'setTxFee',
  'signMessage',
  'signMessageWithPrivKey',
  'signRawTransaction',
  'stop',
  'submitBlock',
  'upTime',
  'validateAddress',
  'verifyChain',
  'verifyMessage',
  'verifyTxOutProof',
  'version',
  'walletLock',
  'walletPassphrase',
  'walletPassphraseChange',
];

for (let method of methods) {
  BitcoinRpc.prototype[method] = _.partial(BitcoinRpc.prototype.call, method.toLowerCase());
  if (method.toLowerCase() != method) {
    BitcoinRpc.prototype[method.toLowerCase()] = _.partial(BitcoinRpc.prototype.call, method.toLowerCase());
  }
}

module.exports = BitcoinRpc;
